framework:
    secret: '%env(APP_SECRET)%'
    session: true
    mailer:
        dsn: '%env(MAILER_DSN)%'
    router:
        default_uri: '%env(resolve:APP_URL)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-host
        - x-forwarded-proto
        - x-forwarded-port
        - x-forwarded-prefix
