# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.JSON
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# Expose your documentation as interactive swagger UI
nelmio_api_doc:
  path: /api/doc
  controller: nelmio_api_doc.controller.swagger_ui
