when@dev:
  debug:
    dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"

web_profiler:
  toolbar: true
  intercept_redirects: false

framework:
  profiler:
    enabled: true
    collect: true

twig:
  debug: true
  strict_variables: true
